[Icon Theme]
Name=multicolor-beta
Comment=next generation theme for inkscape
Hidden=true
Directories=scalable/actions,scalable/apps,symbolic/actions,symbolic/apps

[symbolic/apps]
MinSize=8
Size=16
MaxSize=512
Context=Actions
Type=Scalable

[symbolic/actions]
MinSize=8
Size=16
MaxSize=512
Context=Actions
Type=Scalable

[scalable/actions]
MinSize=8
Size=16
MaxSize=512
Context=Actions
Type=Scalable

[scalable/apps]
MinSize=8
Size=16
MaxSize=512
Context=Actions
Type=Scalable
