[Icon Theme]
Name=nextgeneration
Comment=next generation theme for inkscape
Hidden=true
Directories=scalable/actions,scalable/apps,symbolic/actions,symbolic/apps,16x16/apps,22x22/apps,24x24/apps,32x32/apps,48x48/apps,256x256/apps

[scalable/actions]
MinSize=8
Size=16
MaxSize=512
Context=Actions
Type=Scalable

[scalable/apps]
MinSize=8
Size=16
MaxSize=512
Context=Applications
Type=Scalable

[symbolic/actions]
MinSize=8
Size=16
MaxSize=512
Context=Actions
Type=Scalable

[symbolic/apps]
MinSize=8
Size=16
MaxSize=512
Context=Applications
Type=Scalable

[16x16/apps]
Context=Applications
Size=16
Type=Fixed

[22x22/apps]
Context=Applications
Size=22
Type=Fixed

[24x24/apps]
Context=Applications
Size=24
Type=Fixed

[32x32/apps]
Context=Applications
Size=32
Type=Fixed

[48x48/apps]
Context=Applications
Size=48
Type=Fixed

[256x256/apps]
Context=Applications
Size=256
Type=Fixed

