[Icon Theme]
Name=GtkStock
Inherits=hicolor
Comment=Gtk Stock Icons for Inkscape.app
Example=folder

# Directory list
Directories=16x16/stock,20x20/stock,24x24/stock,32x32/stock,48x48/stock,

[16x16/stock]
Size=16
Context=Stock
Type=fixed

[20x20/stock]
Size=20
Context=Stock
Type=fixed

[24x24/stock]
Size=24
Context=Stock
Type=fixed

[32x32/stock]
Size=32
Context=Stock
Type=fixed

[48x48/stock]
Size=48
Context=Stock
Type=fixed

