#!/bin/bash
#
# Author: Aaron Voisine <aaron@voisine.org>
# Inkscape Modifications: Michael Wybrow <mjwybrow@users.sourceforge.net>

CWD="$(cd "$(dirname "$0")" && pwd)"

BASE="$(echo "$0" | sed -e 's/\/Contents\/Resources\/openDoc/\//')"
cd "$BASE"
exec "$CWD/bin/inkscape" "$@"
