#!/bin/sh
#
# Author: Aaron Voisine <aaron@voisine.org>
# Inkscape Modifications: Michael Wybrow <mjwybrow@users.sourceforge.net>

CWD=`dirname "$0"`

# System version: 3 for Panther, 4 for Tiger, 5 for Leopard
export VERSION=`/usr/bin/sw_vers | grep ProductVersion | cut -f2 -d'.'`

# Warn the user about time-consuming generation of fontconfig caches.
# TODO: Somehow keep in sync with ScriptExec and bin/inkscape. 
#       Ideally refer to $XDG_CACHE_HOME/inkscape everywhere, but how?
test -f "${HOME}/.cache/inkscape/.fccache-new" || exit 12



BASE=`echo "$0" | sed -e 's/\/Contents\/Resources\/script/\//'`
cd "$BASE"
exec "$CWD/bin/inkscape" "$@"
# TODO examine whether it would be wisest to move the code from inkscape shell
# script and getdisplay.sh to here and only keep the real binary in bin. This
# may make things easier on Leopard and may also help using Inkscape on the
# command line.

